In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob
import pandas as pd

import statsmodels.api as sm
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.utils import shuffle

import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [10]:
df=pd.read_csv("drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/rgbarray.csv")
metadata=pd.read_csv('drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/metadata.csv')
labels = np.load("drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/labeldata.npy")

# Modify dataframe for selected features

In [15]:
df['brightness']=metadata['brightness']
df['shutter_speed']=metadata['shutter_speed']
df['exposure_time']=metadata['exposure_time']
#df['iso']=metadata['iso']
df

red_val   green_val   blue_val  shutter_speed  brightness  exposure_time
0    61.841728   83.685791  30.381555          9.024        4.97       0.001919
1    58.776155   80.259737  28.989622          9.024        4.97       0.001919
2    57.559864   79.052525  28.126113          9.024        4.97       0.001919
3    58.090181   78.781991  31.884950          9.024        4.97       0.001919
4    57.787745   78.502028  30.747365          9.024        4.97       0.001919
..         ...         ...        ...            ...         ...            ...
771  82.194736  102.484696  31.684638          9.193        5.17       0.001709
772  81.049292  101.100902  31.487134          9.240        5.19       0.001653
773  80.883341  101.111931  29.385463          9.193        5.13       0.001709
774  80.806641  100.844573  29.671693          9.193        5.13       0.001709
775  81.288360  101.317141  30.076289          9.193        5.14       0.001709

[776 rows x 6 columns]

#Model training

In [16]:
X=df[0:]
Y=labels
X

red_val   green_val   blue_val  shutter_speed  brightness  exposure_time
0    61.841728   83.685791  30.381555          9.024        4.97       0.001919
1    58.776155   80.259737  28.989622          9.024        4.97       0.001919
2    57.559864   79.052525  28.126113          9.024        4.97       0.001919
3    58.090181   78.781991  31.884950          9.024        4.97       0.001919
4    57.787745   78.502028  30.747365          9.024        4.97       0.001919
..         ...         ...        ...            ...         ...            ...
771  82.194736  102.484696  31.684638          9.193        5.17       0.001709
772  81.049292  101.100902  31.487134          9.240        5.19       0.001653
773  80.883341  101.111931  29.385463          9.193        5.13       0.001709
774  80.806641  100.844573  29.671693          9.193        5.13       0.001709
775  81.288360  101.317141  30.076289          9.193        5.14       0.001709

[776 rows x 6 columns]

In [17]:
rs=42
X_train, X_test, y_train, y_test = tts(X, Y, test_size=0.25, random_state=rs)

In [18]:
import joblib

# Support Vector Machine

In [19]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix

clf = make_pipeline(StandardScaler(), SVC(gamma='auto',random_state=rs))
clf.fit(X_train, y_train)

# Save the model as a pickle in a file
#joblib.dump(clf, 'drive/My Drive/Final Year Research/Dataset/Oneplus 5T/data_files/model.pkl')

predicted= clf.predict(X_test)
print("SVM Accuracy:",metrics.accuracy_score(y_test, predicted)*100,"%")

#get the confussion matrix for the model
cm =confusion_matrix(y_test, predicted)  
print("Confussion Matrix : ",cm)

SVM Accuracy: 96.3917525773196 %
Confussion Matrix :  [[50  3  0  0]
 [ 3 35  1  0]
 [ 0  0 54  0]
 [ 0  0  0 48]]


In [ ]:
# Load the model from the file
model = joblib.load('drive/My Drive/Final Year Research/Dataset/Oneplus 5T/datafiles/model.pkl')
 
# Use the loaded model to make predictions
prd=model.predict(X_test)

print("SVM Accuracy:",metrics.accuracy_score(y_test, prd)*100,"%")

SVM Accuracy: 95.33333333333334 %


# Decision Tree

In [20]:
from sklearn import tree
clf = make_pipeline(StandardScaler(), tree.DecisionTreeClassifier(random_state=rs))
#clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)

predicted= clf.predict(X_test)
print("Decesion tree Accuracy:",metrics.accuracy_score(y_test, predicted)*100,"%")

#get the confussion matrix for the model
cm =confusion_matrix(y_test, predicted)  
print("Confussion Matrix : ",cm)

Decesion tree Accuracy: 94.3298969072165 %
Confussion Matrix :  [[48  5  0  0]
 [ 4 35  0  0]
 [ 0  0 54  0]
 [ 0  0  2 46]]
